/home/shantanughosh/DeepColor/Regressor/DeepColor
c37a-s26.ufhpc
Sun Nov  8 05:11:09 EST 2020
Deep Color Regressor
Traceback (most recent call last):
  File "main.py", line 134, in <module>
    colorizer_deep.train_colorizer(augmented_dataset_batch_train, device)
  File "/home/shantanughosh/DeepColor/Regressor/DeepColor/Colorize_deep.py", line 36, in train_colorizer
    colorizer_manager.train(colorizer_train_arguments, device)
  File "/home/shantanughosh/DeepColor/Regressor/DeepColor/Colorizer_Manager.py", line 58, in train
    Utils.plot_loss_epoch(loss_train, loss_plot_path)
  File "/home/shantanughosh/DeepColor/Regressor/DeepColor/utils.py", line 70, in plot_loss_epoch
    plt.savefig(fig_name, dpi=220)
  File "/apps/python/3.7/lib/python3.7/site-packages/matplotlib/pyplot.py", line 842, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/apps/python/3.7/lib/python3.7/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/apps/python/3.7/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/apps/python/3.7/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/apps/python/3.7/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/apps/python/3.7/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/apps/python/3.7/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  [Previous line repeated 1 more time]
  File "/apps/python/3.7/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 593, in print_jpg
    .save(filename_or_obj, format='jpeg', **pil_kwargs))
  File "/apps/python/3.7/lib/python3.7/site-packages/PIL/Image.py", line 2155, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'Plots/Colorizer/Colorizer_Loss_plot.jpeg'
Sun Nov  8 12:59:51 EST 2020
